### ISSUE TITLE
closeAfterClick Error

### ISSUE THREAD

**Issue by ghost** [FreddyFY/material-datepicker#14]
The "closeAfterClick" doesn't seem to work. It seems like it doesn't work in your demo either. The picker always closes no matter the value's set to true/false.

**Comment by FreddyFY** [comment]
@jesslee0124 this option was prepared without making the functionality. 😁

Anyway, I've now built the functionality. It should work with 🔖 v1.0.6

**Comment by ghost** [comment]
@FreddyFY oh I thought the functionality was there because of the demo. Thanks for the quick fix! Cheers!😊
