### ISSUE TITLE
Issue with beginWeek set as "monday" and if the month starts on Sunday

### ISSUE THREAD

**Issue by githieu** [FreddyFY/material-datepicker#18]
Hello,

just found an issue if beginWeek is set as "monday" and if the month starts on Sunday.
As you can see on your own website (https://freddyfy.github.io/material-datepicker/#options-weekBegin), the whole month of September has 1 day shift. 
The September 1st is displayed as a Monday instead of Sunday.

**Comment by FreddyFY** [comment]
Thanks @githieu for this issue.
It's just been fixed.

**Comment by githieu** [comment]
Wow thank you for your very quick action :)
