### ISSUE TITLE
this.picker.querySelector(...) is null

### ISSUE THREAD

**Issue by jhuet** [FreddyFY/material-datepicker#2]
Hey there, i'm not sure i'm initializing this right, but i get a `this.picker.querySelector(...) is null` error when i try your datepicker.

Here's how i've been following your readme usage : https://jsfiddle.net/9jkv8rzx/

Any clue on what i'm doing wrong ? Thanks !

**Comment by FreddyFY** [comment]
Hi there, try to include this file:
https://rawgit.com/FreddyFY/material-datepicker/master/dist/material-datepicker-with-moment-js.js
There is an error with the other version.Thanks for your report!

**Comment by cashpipeplusplus** [comment]
Please update your README!

**Comment by FreddyFY** [comment]
@jhuet Thank you for your bug-report. It has been fixed.
