### ISSUE TITLE
outputFormat always enter today's date

### ISSUE THREAD

**Issue by alex-mora80** [FreddyFY/material-datepicker#22]
When you use the outputFormat option always set today's date. It should be able to format the date of the input value.

**Comment by FreddyFY** [comment]
Hi Alex, I can't reproduce this issue. 
In my tests this works fine
```html
    <input type="text" id="materialpicker011" value="22.08.19" >
    <script>
      const materialPicker011 = new MaterialDatepicker('#materialpicker011', {
        // lang: "fa",
        outputFormat: "DD.MM.YY"
      });
    </script>
```

Can you send a codepen with this issue?
