### ISSUE TITLE
Should it really set a new date on ever document.keyup?

### ISSUE THREAD

**Issue by jamesgibson14** [FreddyFY/material-datepicker#24]
https://github.com/FreddyFY/material-datepicker/blob/56ebae03d09777dbc0e4b3bcd48529725b0287c2/src/javascript/material-datepicker.es6#L120

**Comment by FreddyFY** [comment]
This `keyup` was made to change the year faster, without clicking always the arrows.
`onblur` is to late. You could add a timeout to the `keyup`.

Or do you have another idea?
