### ISSUE TITLE
next month button can skip short months

### ISSUE THREAD

**Issue by cashpipeplusplus** [FreddyFY/material-datepicker#3]
To reproduce, select Jan 31, then click the next month button.  Instead of Feb 28, Mar 3 is selected.  Clicking prev month then takes you to Feb 3.

**Comment by FreddyFY** [comment]
@cashpipeplusplus Thank you for your bug report

**Comment by cashpipeplusplus** [comment]
Thank you for the fast fix!  All I had to do was refresh the page I'm building and it's working beautifully!
