### ISSUE TITLE
Uncaught TypeError: Cannot create property 'innerHTML' on string ' '

### ISSUE THREAD

**Issue by p10r** [FreddyFY/material-datepicker#9]
Hey,

I'm running into the following error when using the datepicker:

![uncaughttypeerr](https://user-images.githubusercontent.com/23278849/39917790-e8e94b30-550e-11e8-8808-240a17612474.png)

It appears when opening the datepicker/clicking the input field.
I tried it on different machines/browsers, but it seems like it is in context with newer browser versions.

OS/Browser:
Arch Linux/Chromium Version 66.0.3359.139, Firefox 59.0.2 - not working
Ubuntu/Firefox 59.0.2 - not working
Ubuntu/Firefox 38.0.4 - **working**

The result is that the datepicker is not fully functional (e.g. not closing after date pick etc)
Any help would be appreciated.

Thanks!

**Comment by grandadmiralmcb** [comment]
I am getting this same issue as well in my application as well.  I made a very simple app with only one input field and the code taken from the website to make that one input field populate and in the most meager example that I could build this error occurs.
